data:
  clean_data_path: '../../Datasets/clean_dir'
  noisy_data_path: '../../Datasets/noisy_dir'
  clean_chunk_path: '../../Chunks/y-data'
  noisy_chunk_path: '../../Chunks/x-data'
  asr_data_path: '../../Datasets/LJSpeech-1.1'
  sample_rate: 16000
  data_duration: 10

model:
  activation: 'relu'
  output_activation: 'sigmoid'
  optimizer: 'adam'
  loss: 'mse'

training:
  epochs: 1
  batch_size: 1
  validation_split: 0.2

testing:
  noisy_data_path: '../../Datasets/noisy_dir'
  clean_data_path: '../../Datasets/clean_dir'
  unet_model_path: 'model.keras'
  autoencoder_model_path: 'autoencoder.keras'

inference:
  noisy_data_path: '../../Datasets/noisy_dir'
  denoised_data_path: '../../Datasets/denoised_dir'

asr_training:
  frame_length: 256
  frame_step: 160
  fft_length: 384
  batch_size: 32
  epochs: 1
  num_of_samples: 30

asr_testing:
  frame_length: 256
  frame_step: 160
  fft_length: 384
  batch_size: 32

wave2vec:
  model_name: 'facebook/wav2vec2-base-960h'
  sample_rate: 16000
