data:
  clean_data_path: '../Dataset/clean_dir'
  noisy_data_path: '../Dataset/noisy_dir'
  clean_chunk_path: '../Chunks/y-data'
  noisy_chunk_path: '../Chunks/x-data'
  sample_rate: 16000
  data_duration: 10

model:
  activation: 'relu'
  output_activation: 'sigmoid'
  optimizer: 'adam'
  loss: 'mse'

training:
  epochs: 1
  batch_size: 1
  validation_split: 0.2

testing:
  noisy_data_path: 'Dataset/noisy_dir'
  clean_data_path: 'Dataset/clean_dir'
  unet_model_path: 'Model/model.keras'
  autoencoder_model_path: 'Model/autoencoder.keras'